/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "PortableCraftingInvs-parent"
include(":PortableCraftingInvs-v1_20_R3")
include(":PortableCraftingInvs-v1_20_R2")
include(":PortableCraftingInvs-Common")
include(":PortableCraftingInvs-Core")
include(":PortableCraftingInvs-v1_19_R1")
include(":PortableCraftingInvs-v1_20_R1")
include(":PortableCraftingInvs-v1_19_R3")
include(":PortableCraftingInvs-v1_19_R2")
include(":PortableCraftingInvs-API")
project(":PortableCraftingInvs-v1_20_R3").projectDir = file("v1_20_R3")
project(":PortableCraftingInvs-v1_20_R2").projectDir = file("v1_20_R2")
project(":PortableCraftingInvs-Common").projectDir = file("Common")
project(":PortableCraftingInvs-Core").projectDir = file("core")
project(":PortableCraftingInvs-v1_19_R1").projectDir = file("v1_19_R1")
project(":PortableCraftingInvs-v1_20_R1").projectDir = file("v1_20_R1")
project(":PortableCraftingInvs-v1_19_R3").projectDir = file("v1_19_R3")
project(":PortableCraftingInvs-v1_19_R2").projectDir = file("v1_19_R2")
project(":PortableCraftingInvs-API").projectDir = file("API")
