########################################################################################
#                                                                                      #
#                        _____      _   _   _                                          #
#                       / ____|    | | | | (_)                                         #
#                      | (___   ___| |_| |_ _ _ __   __ _ ___                          #
#                       \___ \ / _ \ __| __| | '_ \ / _` / __|                         #
#                       ____) |  __/ |_| |_| | | | | (_| \__ \                         #
#                      |_____/ \___|\__|\__|_|_| |_|\__, |___/                         #
#                                                    __/ |                             #
#                                                   |___/                              #
#                                                                                      #
########################################################################################
#
# This file can be used to enable or disable all parts of the plugin.
#
# If you have questions you can post an issue on Github
# (https://github.com/ItsSchatten/PortableCraftingInv/issues) Also helpful if you want to
# see the code for the plugin.
# You can also message me on Discord (Schatten#4113)
#

# I do not recommend you enable this unless you want to have your console be filled with messages.
debug: false

# If this is set to true and you add more then the required amount of arguments
# the plugin will send you a message saying so.
use-too-many-args: true

# If this is set to true, when there is an update to the plugin admins with the correct
# permissions (pci.update) and console will be notified. You can set a custom message
# in the message.yml if you want.
use-updater: true

# If a user was to use the command /pci and not provide any arguments to the command,
# we send the help message along with the wrong arguments message.
use-help-if-no-args: true

# If enabled the plugin will send statistics to BStats.
metrics: true

# ------------------------------------------------------------------------------------- #
#                                                                                       #
#                                   Crafting Features                                   #
#                                                                                       #
# ------------------------------------------------------------------------------------- #

# Enable or disable the use of the /anvil command.
use-anvil: true

# Enable or disable the use of the /craft command.
use-crafting: true

# Enable or disable the use of the /enchanttable command.
use-enchanttable: true

# Enable or disable the use of the /enderchest command.
use-enderchest: true

# Should we only allow players to deposit items into their enderchest when using the command?
ender-chest-restrictions: false

# ------------------------------------------------------------------------------------- #
#                                                                                       #
#                                     Enable sounds                                     #
#                                                                                       #
# ------------------------------------------------------------------------------------- #

# When true, instead of the default sound playing, we randomize the sound pitch to make it higher or lower.
use-random-sound-pitch: true

# Enable or disable the sound when opening the anvil with /anvil.
use-anvil-sounds: false

# Enable or disable the sound when opening the crafting table with /craft.
use-crafting-sounds: false

# Enable or disable the sound when opening the enchantment table with /enchanttable.
use-enchanttable-sounds: false

# Enable or disable the sound when opening the enderchest with /enderchest.
use-enderchest-sounds: true

# ------------------------------------------------------------------------------------- #
#                                                                                       #
#                                         Sounds                                        #
#                                                                                       #
# Want to use different sounds?                                                         #
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html                        #
# ------------------------------------------------------------------------------------- #

# This sound is played when opening the anvil using /anvil.
anvil-open-sound: BLOCK_ANVIL_HIT

# This sound is played when opening the crafting table using /craft.
crafting-open-sound: BLOCK_WOOD_PLACE

# This sound is played when opening the enchantmenttable using /enchantable.
enchanttable-open-sound: BLOCK_ENCHANTMENT_TABLE_USE

# This sound is played when opening the enderchest using /enderchest
enderchest-open-sound: BLOCK_ENDER_CHEST_OPEN