########################################################################################
#                                                                                      #
#                        _____      _   _   _                                          #
#                       / ____|    | | | | (_)                                         #
#                      | (___   ___| |_| |_ _ _ __   __ _ ___                          #
#                       \___ \ / _ \ __| __| | '_ \ / _` / __|                         #
#                       ____) |  __/ |_| |_| | | | | (_| \__ \                         #
#                      |_____/ \___|\__|\__|_|_| |_|\__, |___/                         #
#                                                    __/ |                             #
#                                                   |___/                              #
#                                                                                      #
########################################################################################
#
# This file can be used to enable or disable all parts of the plugin.
#
# If you have questions you can post an issue on BitBucket
# (https://bitbucket.org/itsschatten/portablecraftinginvs/issues) Also helpful if you want to
# see the code for the plugin.
# You can also message me on Discord (Schatten#4113)
#

# I do not recommend you enable this unless you want to have your console be filled with messages.
debug: false

# If this is set to true and you add more then the required amount of arguments
# the plugin will send you a message saying so.
use-too-many-args: true

# If this is set to true, when there is an update to the plugin admins with the correct
# permissions (pci.update) and console will be notified. You can set a custom message
# in the message.yml if you want.
use-updater: true

# If a user was to use the command /pci and not provide any arguments to the command,
# we send the help message along with the wrong arguments message.
use-help-if-no-args: true

# If enabled the plugin will send statistics to BStats. Which you can see here: https://bstats.org/plugin/bukkit/PortableCraftingInvs
metrics: true

# ------------------------------------------------------------------------------------- #
#                                                                                       #
#                                   Crafting Features                                   #
#                                                                                       #
# ------------------------------------------------------------------------------------- #

# Enable or disable the use of the /anvil command.
use-anvil: true

# Enable or disable the use of the /craft command.
use-crafting: true

# Enable or disable the use of the /enchanttable command.
use-enchanttable: true

# Enable or disable the ability to define a max level for enchanting.
allow-max-level-argument: true

# Set the maximum allowed level when it's defined.
maximum-enchant-level: 30

# Enable or disable the use of the /enderchest command.
use-enderchest: true

# Should we only allow players to deposit items into their enderchest when using the command?
ender-chest-restrictions: false

# Enable or disable the use of the /grindstone command.
use-grindstone: true

# Enable or disable the use of the /cartography command.
use-cartography: true

# Enable or disable the use of /loom command.
use-loom: true

# Enable or disable the use of /stonecutter command.
use-stonecutter: true

# ------------------------------------------------------------------------------------- #
#                                                                                       #
#                                     Sign Features                                     #
#                                                                                       #
# ------------------------------------------------------------------------------------- #

# Enable or disable the use of signs.
use-signs: true

# Should we only allow players to break signs if they are shift clicking?
require-shift-click-to-break-signs: true

# Enable or disable the anvil sign.
use-anvil-sign: true

# Enable or disable the anvil sign.
use-cartography-sign: true

# Enable or disable the anvil sign.
use-crafting-sign: true

# Enable or disable the anvil sign.
use-enchanttable-sign: true

# Enable or disable the anvil sign.
use-enderchest-sign: true

# Enable or disable the grindstone sign.
use-grindstone-sign: true

# Enable or disable the loom sign.
use-loom-sign: true

# Enable or disable the stonecutter sign.
use-stonecutter-sign: true

# ------------------------------------------------------------------------------------- #
#                                                                                       #
#                                     Enable sounds                                     #
#                                                                                       #
# ------------------------------------------------------------------------------------- #

# When true, instead of the default sound playing, we randomize the sound pitch to make it higher or lower.
use-random-sound-pitch: true

# Enable or disable the sound when opening the anvil with /anvil.
use-anvil-sounds: false

# Enable or disable the sound when opening the crafting table with /craft.
use-crafting-sounds: false

# Enable or disable the sound when opening the enchantment table with /enchanttable.
use-enchanttable-sounds: false

# Enable or disable the sound when opening the enderchest with /enderchest.
use-enderchest-sounds: true

# Enable or disable the sound when opening the grindstone.
use-grindstone-sounds: false

# Enable or disable the sound when opening the cartography table.
use-cartography-sounds: false

# Enable or disable the sound when opening the loom.
use-loom-sounds: false

# Enable or disable the sound when opening the stone cutter.
use-stonecutter-sounds: false

# ------------------------------------------------------------------------------------- #
#                                                                                       #
#                                         Sounds                                        #
#                                                                                       #
# Want to use different sounds?                                                         #
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html                        #
# ------------------------------------------------------------------------------------- #

# This sound is played when opening the anvil using /anvil.
anvil-open-sound: BLOCK_ANVIL_HIT

# This sound is played when opening the crafting table using /craft.
crafting-open-sound: BLOCK_WOOD_PLACE

# This sound is played when opening the enchantmenttable using /enchantable.
enchanttable-open-sound: BLOCK_ENCHANTMENT_TABLE_USE

# This sound is played when opening the enderchest using /enderchest
enderchest-open-sound: BLOCK_ENDER_CHEST_OPEN

# This sound is played when opening the grindstone.
grindstone-open-sound: BLOCK_CHEST_OPEN

# This sound is played when opening the loom.
loom-open-sound: BLOCK_CHEST_OPEN

# This sound is played when opening the cartography table.
cartography-open-sound: BLOCK_CHEST_OPEN

# This sound is played when opening the stone cutter.
stonecutter-open-sound: BLOCK_CHEST_OPEN
