name: Bug Report
description: Report a bug or issue with the plugin or how it functions.
labels: [ "type: bug", "priority: normal", "status: awaiting confirmation" ]
title: "[BUG] | "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out a bug report! Please fill out the fields below with as much information and detail as you can.
  - type: textarea
    id: version
    attributes:
      label: "PCI Information"
      description: "If you're unsure run the command \"/pci version\" in-game or in your console."
      placeholder: "1.0.0"
    validations:
      required: true
  - type: textarea
    id: bug_description
    attributes:
      label: "Describe the Bug"
      description: "Describe the bug in full detail, explain what happened and how to reproduce this bug."
      placeholder: |
        Anvils delete items!

        1. Run the command '/anvil'
        2. Place any item into any slot in the anvil.
        3. Close the anvil and the item will not be returned to the player!
        4. Profit.
    validations:
      required: true
  - type: textarea
    id: plugin_list
    attributes:
      label: "What plugins are you running?"
      description: "Providing a list of your plugins may be useful to determine incompatibilities with PCI."
      placeholder: |
        PlaceholderAPI, PortableCraftingInvs, EssentialsX, EssentialsXChat...
    validations:
      required: false
  - type: textarea
    id: anything_else_to_add
    attributes:
      label: "Anything else?"
      description: "Anything else you think I should be aware of."
    validations:
      required: false
