/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.itsschatten.portablecrafting.java-conventions")
}

dependencies {
    api(project(":PortableCraftingInvs-Common"))
    api("com.itsschatten.portablecrafting:API:1.0.0")
    api(project(":PortableCraftingInvs-v1_19_R1"))
    api(project(":PortableCraftingInvs-v1_19_R2"))
    api(project(":PortableCraftingInvs-v1_19_R3"))
    api(project(":PortableCraftingInvs-v1_20_R1"))
    api(project(":PortableCraftingInvs-v1_20_R2"))
    api(project(":PortableCraftingInvs-v1_20_R3"))
    compileOnly("org.spigotmc:spigot-api:1.20.3-R0.1-SNAPSHOT")
}

description = "PortableCraftingInvs-Core"
