/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.codemc.org/repository/maven-public")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
    }
}

dependencies {
    api("com.itsschatten.libs:ShadowLibs:1.0.9")
    api("com.shanebeestudios.api:VirtualFurnace-API:1.1.5-Schatten")
    api("org.bstats:bstats-bukkit:3.0.1")
    compileOnly("org.projectlombok:lombok:1.18.26")
}

group = "com.itsschatten.portablecrafting"
version = "1.7.12"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
