/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.itsschatten.portablecrafting.java-conventions")
}

dependencies {
    api("org.spigotmc:spigot-api:1.19.2-R0.1-SNAPSHOT")
    api(project(":PortableCraftingInvs-API"))
}

description = "PortableCraftingInvs-Common"
