/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.itsschatten.portablecrafting.java-conventions")
}

dependencies {
    api(project(":PortableCraftingInvs-Common"))
    api("com.itsschatten.portablecrafting:API:1.0.0")
    compileOnly("org.spigotmc:spigot:1.19.4-R0.1-SNAPSHOT")
}

description = "PortableCraftingInvs-v1_19_R3"
