name: PortableCraftingInvs
version: ${project.version}
main: ${main}
author: ${author}
description: ${description}
api-version: "1.15"
soft-depend: [Essentials]
permissions:
  pci.*:
    default: false
    description: "Gives all permissions to a user (besides reload and update), useful if you don't want to op someone."
    children:
      pci.anvil: true
      pci.anvil.other: true
      pci.craft: true
      pci.craft.other: true
      pci.enchanttable: true
      pci.enchanttable.other: true
      pci.enderchest: true
      pci.enderchest.other: true
      pci.grindstone: true
      pci.grindstone.other: true
      pci.loom: true
      pci.loom.other: true
      pci.cartography: true
      pci.cartography.other: true
      pci.stonecutter: true
      pci.stonecutter.other: true
      pci.sign.*: true


  pci.anvil:
    default: op
    description: "The permission needed to be able to run the /anvil command."

  pci.anvil.other:
    default: op
    description: "This permission is needed for players to open the anvil for another player."

  pci.craft:
    default: op
    description: "This permission is needed to be able to run the /craft command."

  pci.craft.other:
    default: op
    description: "This permission is needed to be able to run the /craft command for another player."

  pci.enchanttable:
    default: op
    description: "This permission is needed to be able to use the /enchanttable command."

  pci.enchanttable.other:
    default: op
    description: "This permission is needed to be able to use the /enchanttable command on another player."

  pci.enderchest:
    default: op
    description: "This permission is needed to be able to use the /enderchest command."

  pci.enderchest.other:
    default: op
    description: "This permission is needed to be able to use the /enderchest command to open another player's enderchest."

  pci.reload:
    default: op
    description: "This permission allows a user to reload the configuration files."
  pci.update:
    default: op
    description: "Users with this permission will be able to see when an update is available for the plugin."

  pci.grindstone:
    description: "The permission needed to open the grindstone."
    default: op

  pci.grindstone.other:
    description: "The permission needed to open the grindstone for someone else."
    default: op

  pci.smithingtable:
    description: "The permission needed to open the smithing table."
    default: op

  pci.smithingtable.other:
    description: "The permission needed to open the smithing table for someone else."
    default: op

  pci.loom:
    description: "The permission needed to open the loom"
    default: op

  pci.loom.other:
    description: "The permission needed to open the loom for someone else."
    default: op

  pci.cartography:
    description: "The permission needed to open the cartography."
    default: op

  pci.cartography.other:
    description: "The permission needed to open the cartography table for someone else."
    default: op

  pci.stonecutter:
    description: "The permission needed to open the stone cutter."
    default: op

  pci.stonecutter.other:
    description: "The permission needed to open the stone cutter for someone else."
    default: op

  pci.sign.create:
    description: "Ability to create signs."
    default: op

  pci.sign.*:
    description: "Gives all sign perms."
    default: false
    children:
      pci.sign.create: true
      pci.sign.use.*: true
      pci.sign.anvil: true
      pci.sign.cartography: true
      pci.sign.crafting-table: true
      pci.sign.enchanttable: true
      pci.sign.endechest: true
      pci.sign.grindstone: true
      pci.sign.loom: true
      pci.sign.stonecutter: true

  pci.sign.use.*:
    default: op
    description: "Gives all use permissions."
    children:
      pci.sign.anvil.use: true
      pci.sign.cartography.use: true
      pci.sign.crafting-table.use: true
      pci.sign.enchanttable.use: true
      pci.sign.enderchest.use: true
      pci.sign.grindstone.use: true
      pci.sign.loom.use: true
      pci.sign.stonecutter.use: true
      pci.sign.smithingtable.use: true

  pci.sign.anvil:
    default: op
    description: "Create an anvil sign."
  pci.sign.cartography:
    default: op
    description: "Create a cartography sign."
  pci.sign.crafting-table:
    default: op
    description: "Create a crafting table sign."
  pci.sign.enchanttable:
    default: op
    description: "Create an enchanttable sign."
  pci.sign.endechest:
    default: op
    description: "Create an enderchest sign."
  pci.sign.grindstone:
    default: op
    description: "Create a grindstone sign."
  pci.sign.loom:
    default: op
    description: "Create a loom sign."
  pci.sign.stonecutter:
    default: op
    description: "Create a stone cutter sign."
  pci.sign.smithingtable:
    default: op
    description: "Create the smithing table sign."


  pci.sign.anvil.use:
    default: op
    description: "Use an anvil sign."
  pci.sign.cartography.use:
    default: op
    description: "Use a cartography sign."
  pci.sign.crafting-table.use:
    default: op
    description: "Use a crafting table sign."
  pci.sign.enchanttable.use:
    default: op
    description: "Use an enchanttable sign."
  pci.sign.endechest.use:
    default: op
    description: "Use an enderchest sign."
  pci.sign.grindstone.use:
    default: op
    description: "Use a grindstone sign."
  pci.sign.loom.use:
    default: op
    description: "Use a loom sign."
  pci.sign.stonecutter.use:
    default: op
    description: "Use a stone cutter sign."
  pci.sign.smithingtable.use:
    default: op
    description: "Use a smithing table sign."
